### ISSUE TITLE
First two lines in usage section don't work

### ISSUE THREAD

**Issue by davidanthoff** [JuliaPy/Pandas.jl#13]
When I start with the code in the usage section, I get this:
````
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.1 (2017-03-05 13:25 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using Pandas

julia> df = DataFrame([:age=>[27, 29, 27], :name=>["James", "Jill", "Jake"]])
{0: {0: 'age', 1: 'name'}, 1: {0: array([27, 29, 27], dtype=int64), 1: ['James', 'Jill', 'Jake']}}
````
And then nothing that follows works. I assume things go wrong here all ready, it seems to me that ``df`` is just a dict here, not a pandas DataFrame?

**Comment by fuzzybear3965** [comment]
@davidanthoff It seems that it [may be best for Pandas.jl to avoid conversion of DataFrames](https://github.com/JuliaPy/PyCall.jl/issues/376#issuecomment-293411255). I would recommend trying what I had tried to see if that works a bit better for you.

**Comment by davidanthoff** [comment]
I don't really know much about Pandas.jl, I just noticed that it seems not to work at all on my system, I think really @malmaud will have to look into this.

**Comment by malmaud** [comment]
At some point, there was a change to PyCall.jl that broke Pandas.jl. I'll fix it soon (hopefully today).

**Comment by malmaud** [comment]
Fixed in master - note the Readme has changed (it was still referring to syntax that was for Julia .4).

**Comment by davidanthoff** [comment]
Hm, this still doesn't work for me. I'm on ``master``, and this is what I get if I just follow the README:
````
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.1 (2017-03-05 13:25 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using Pandas

julia> df = DataFrame(Dict(:age=>[27, 29, 27], :name=>["James", "Jill", "Jake"]))
{'age': {0: 27, 1: 29, 2: 27}, 'name': {0: 'James', 1: 'Jill', 2: 'Jake'}}


julia> describe(df)
ERROR: KeyError: key "describe" not found
 in getindex(::PyCall.PyObject, ::String) at C:\Users\anthoff\.julia\v0.5\PyCall\src\PyCall.jl:266
 in #describe#107(::Array{Any,1}, ::Function, ::Pandas.DataFrame) at C:\Users\anthoff\.julia\v0.5\Pandas\src\Pandas.jl:120
 in describe(::Pandas.DataFrame) at C:\Users\anthoff\.julia\v0.5\Pandas\src\Pandas.jl:119

julia>
````

**Comment by malmaud** [comment]
Try `Pkg.checkout("PyCall", "jmm/dict_convert")`, restarting your Julia session, and trying again.

**Comment by davidanthoff** [comment]
That seems to work. I'm getting a warning that no working GUI backend was found for matplotlib, but things seem to work.

**Comment by malmaud** [comment]
I just pushed a change to Pandas.jl that I *think* will let you work with the current version of PyCall - sorry that I can't test, since I can't reproduce your issue.

**Comment by davidanthoff** [comment]
Constructing a DataFrame now works on ``master`` with the current version of PyCall, but then ``describe`` seems to not work:
````
julia> df = DataFrame(Dict(:age=>[27, 29, 27], :name=>["James", "Jill", "Jake"]))
   age   name
0   27  James
1   29   Jill
2   27   Jake


julia> describe(df)
Dict{Any,Any} with 1 entry:
  "age" => Dict{Any,Any}(Pair{Any,Any}("50%",27.0),Pair{Any,Any}("min",27.0),Pair{Any,Any}("max",29.0),Pair{Any,Any}("count",3.0),Pair{Any,Any}("25%",27.0),Pair{Any,Any}("mean",27.6667),Pair{Any,Any}("75%",28.0),Pair{Any,Any}("std",1.1547))
````

**Comment by malmaud** [comment]
*Now*, at long last, it should be fully fixed.

**Comment by davidanthoff** [comment]
Now almost everything works, except the following line:
````
julia> query(df3, :(income>85))
Dict{Any,Any} with 3 entries:
  "name"   => Dict{Any,Any}(Pair{Any,Any}(0,"James"),Pair{Any,Any}(1,"Jill"))
  "income" => Dict{Any,Any}(Pair{Any,Any}(0,101),Pair{Any,Any}(1,87))
  "age"    => Dict{Any,Any}(Pair{Any,Any}(0,27),Pair{Any,Any}(1,29))
````

**Comment by malmaud** [comment]
Everything should work now with PyCall master.
